# UV configuration file

# Resolution settings
resolution = "highest"

# Cache settings
no-cache = false

# Python version preferences
python-preference = "3.12"

# Dependencies
exclude-newer = []

# Development settings
compile-bytecode = true
